-- Technographic Hunter - Supabase Table Setup
-- Run this in your Supabase SQL Editor

-- Create the main leads table
create table technographic_leads (
  id bigint generated by default as identity primary key,
  url text not null unique,
  detected_cms text, -- 'shopify', 'other'
  has_pixel boolean default false,
  has_ga4 boolean default false,
  ssl_error boolean default false,
  neglected boolean default false,
  last_scanned_at timestamp with time zone default timezone('utc'::text, now()),
  
  -- Indexes for fast API queries
  constraint technographic_leads_url_key unique (url)
);

-- Create index on detected_cms for fast filtering
create index idx_detected_cms on technographic_leads(detected_cms);
create index idx_has_pixel on technographic_leads(has_pixel);
create index idx_has_ga4 on technographic_leads(has_ga4);
create index idx_last_scanned_at on technographic_leads(last_scanned_at desc);

-- Enable Row Level Security
alter table technographic_leads enable row level security;

-- Create policy for Service Role (Python script) to insert/update
create policy "Service Role can do everything"
on technographic_leads
for all
to service_role
using (true)
with check (true);

-- Create policy for authenticated users to read (API endpoint)
create policy "Authenticated users can read"
on technographic_leads
for select
to authenticated
using (true);

-- Verify setup
select 'Technographic Hunter table created successfully!' as status;
